[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
# family = "MesloLGS NF"
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_title = true
decorations = "none"
dynamic_padding = false
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 2
y = 2

[mouse]
hide_when_typing = false

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

# Do not use for hyperlinks
# [[hints.enabled]]
# command = "xdg-open"
# hyperlinks = true
