[mgr]
prepend_keymap = [
    { on = "<Delete>", run = 'remove --force', desc = "Trash selected file(s) without confirmation" },
    { on = "<Enter>",  run = 'plugin smart-enter', desc = "Enter the child directory, or open the file" },
    { on = "!",        run = 'shell "$SHELL" --block', desc = "Open $SHELL here" }
]
