#theme = "slick" 
#theme = "solarized-dark"
#theme = "nord-dark"
theme = "gruvbox-dark"
[icons]
name = "awesome" # seems not needed to specify awesome6 
[icons.overrides]
pomodoro = "\ue082"
time = "\uf073" # Needed with pro
# not matching below
weather_sun = "\uf185"
weather_default = "\uf185"

## Webcam controls
[[block]]
block = "custom"
command =  "echo \uf355"
on_click = "webcam-control.sh set pan_absolute -1"
interval = "once"

[[block]]
block = "custom"
command =  "echo \uf356"
on_click = "webcam-control.sh set pan_absolute 1"
interval = "once"

[[block]]
block = "custom"
command =  "echo \uf146"
on_click = "webcam-control.sh set tilt_absolute -1"
interval = "once"

[[block]]
block = "custom"
command =  "echo \uf5e5"
on_click = "webcam-control.sh set tilt_absolute 1"
interval = "once"

[[block]]
block = "custom"
command =  "echo \uf146" # should be f010 for minus magnifying glass
on_click = "webcam-control.sh set zoom_absolute -1"
interval = "once"

[[block]]
block = "custom"
command =  "echo \uf00e"
on_click = "webcam-control.sh set zoom_absolute 1"
interval = "once"

## Rest 

[[block]]
block = "weather"
# format = "{weather} ({location}) {temp}, {wind} m/s {direction}"
format = "{weather_verbose} {temp}, {wind_kmh} km/h {direction}"
service = { name = "openweathermap", units = "metric" }

# [[block]]
# Not used anymore as there is a pomodoro block, more integrated etc.
# block = "custom"
# command = "i3-gnome-pomodoro status --always | sed 's/Pomodoro/\uf2f2/g' | sed 's/Break/\uf4d8/g'"
# on_click = "i3-gnome-pomodoro start-stop"
# interval = 60

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Break time!"
break_message = "Focus time!"
notifier = "notifysend"

[[block]]
block = "custom"
command = "echo \uf2d2"
on_click = "rofi -modi window -no-fixed-num-lines -theme solarized -font 'hack 16' -show window -icon-theme 'Papirus' -show-icons -location 3"
interval = "once"

[[block]]
block = "custom"
command = "echo \uf70c"
on_click = "idasen-controller --stand"
interval = "once"

[[block]]
block = "custom"
command =  "echo \uf6c1"
on_click = "idasen-controller --sit"
interval = "once"

[[block]]
block = "custom"
command = "echo \uf53f"
on_click = "zenity --color-selection"
interval = "once"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used} /{mem_total}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "battery"
interval = 60
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 5
format = "%d-%m %R"
on_click = "zenity --calendar"

[[block]]
block = "custom"
interval = 60
signal = 0 # 0 corresponds to -SIGRTMIN that will be sent at the end of on_click below
command = "mic-icon.sh"
on_click = "pactl get-default-source | xargs -I% pactl set-source-mute % 'toggle';pkill -SIGRTMIN i3status-rs"

# ---- Not used but these blocks could be useful

# [[block]]
# block = "nvidia_gpu"
# label = "GPU"
# show_memory = false
# show_clocks = false
# interval = 1

# Seems to be problematic... when going full screen, etc.
# at least tested in November 2022
# [[block]]
# block = "music"
# on_collapsed_click = "spotify"

# In fact not using it as sound at 100% and control with DX3 Pro+
# issue with icon as well, and not needed for headphone
# however other interesting option if needed
# [[block]]
# block = "sound"
# headphones_indicator = true

# Not needed, only working on laptop
# [[block]]
# block = "xrandr"
# icons = true
# resolution = true

