[theme]
#theme = "slick" 
#theme = "solarized-dark"
theme = "nord-dark"
#theme = "gruvbox-dark"
[icons]
icons = "awesome6"
[icons.overrides]
pomodoro = "\ue082"
time = "\uf073" # Needed with pro
# weather_sun = "\uf185" # Sun looks like a gear
weather_sun = "\uf892"
weather_default = "\uf892"
notification = "\uf075"

## Webcam controls
# [[block]]
# block = "custom"
# command =  "echo \uf355"
# on_click = "webcam-control.sh set pan_absolute -1"
# interval = "once"

# [[block]]
# block = "custom"
# command =  "echo \uf356"
# on_click = "webcam-control.sh set pan_absolute 1"
# interval = "once"

# [[block]]
# block = "custom"
# command =  "echo \uf146"
# on_click = "webcam-control.sh set tilt_absolute -1"
# interval = "once"

# [[block]]
# block = "custom"
# command =  "echo \uf5e5"
# on_click = "webcam-control.sh set tilt_absolute 1"
# interval = "once"

# [[block]]
# block = "custom"
# command =  "echo \uf146" # should be f010 for minus magnifying glass
# on_click = "webcam-control.sh set zoom_absolute -1"
# interval = "once"

# [[block]]
# block = "custom"
# command =  "echo \uf00e"
# on_click = "webcam-control.sh set zoom_absolute 1"
# interval = "once"

# Dunst toggle notification
[[block]]
block = "custom"
# cycle = ["dunstctl set-paused false; echo \U0001f311", "dunstctl set-paused true; echo \U0001f315"]
cycle = ["dunstctl set-paused false; echo '{\"icon\":\"notification\",\"state\":\"Idle\", \"text\": \"\"}'",
         "dunstctl set-paused true; echo '{\"icon\":\"notification\",\"state\":\"Warning\", \"text\": \"\"}'"]
interval = "once"
json = true
[[block.click]]
button = "left"
action = "cycle"

[[block]]
block = "weather"
format = " $icon $weather $temp, $wind_kmh km/h $direction "
[block.service]
name = "openweathermap"
units = "metric"

[[block]]
block = "custom"
command = "so-status.sh"
interval = 600

# [[block]]
# block = "pomodoro"
# length = 25
# break_length = 5
# message = "Break time!"
# break_message = "Focus time!"
# notifier = "notifysend"

[[block]]
block = "custom"
command = "echo \uf2d2"
interval = "once"
[[block.click]]
button = "left"
# Align to i3 config
cmd = "rofi -modi window -no-fixed-num-lines -show window -location 3"

[[block]]
block = "custom"
command = "echo \uf70c"
interval = "once"
[[block.click]]
button = "left"
cmd = "idasen-controller --stand"

[[block]]
block = "custom"
command =  "echo \uf6c1"
interval = "once"
[[block.click]]
button = "left"
cmd = "idasen-controller --sit"

[[block]]
block = "custom"
command = "echo \uf1ec"
interval = "once"
[[block.click]]
button = "left"
cmd = "io.elementary.calculator"

[[block]]
block = "custom"
command = "echo \uf53f"
interval = "once"
[[block.click]]
button = "left"
cmd = "zenity --color-selection"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 50.0
alert = 20.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_used / $mem_total "
# format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
format_alt = " $icon $frequency "

[[block]]
block = "load"
format = " $icon $1m.eng(w:4) "
interval = 5

[[block]]
block = "nvidia_gpu"
interval = 5
format = " $icon $utilization $temperature $clocks"

[[block]]
block = "battery"
interval = 60
format = " $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "time"
interval = 10
format = " $timestamp.datetime(f:'%d-%m %R') "
[[block.click]]
button = "left"
cmd = "zenity --calendar"

[[block]]
block = "custom"
interval = 60
signal = 0 # corresponds to -SIGRTMIN sent at the end of click below
command = "mic-icon.sh"
[[block.click]]
button = "left"
cmd = "pactl get-default-source | xargs -I% pactl set-source-mute % 'toggle';pkill -SIGRTMIN i3status-rs"

[[block]]
block = "custom"
interval = 60
command = "sink-icon.sh"
[[block.click]]
button = "left"
cmd = "pkill pasystray;pasystray"
[[block.click]]
button = "right"
cmd = "pavucontrol"


# ---- Not used but these blocks could be useful

# [[block]]
# block = "nvidia_gpu"
# label = "GPU"
# show_memory = false
# show_clocks = false
# interval = 1

# Seems to be problematic... when going full screen, etc.
# at least tested in November 2022
# [[block]]
# block = "music"
# on_collapsed_click = "spotify"

# In fact not using it as sound at 100% and control with DX3 Pro+
# issue with icon as well, and not needed for headphone
# however other interesting option if needed
# [[block]]
# block = "sound"
# headphones_indicator = true

# Not needed, only working on laptop
# [[block]]
# block = "xrandr"
# icons = true
# resolution = true
